### ISSUE TITLE
compare: error if a benchmark stops building

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustc-perf#7] opened 2015-06-18 05:51 UTC
If a benchmark builds in build a, but not build b then we get a fatal JS error.

**Comment by Mark-Simulacrum** [comment] 2016-08-23 20:00
I cannot reproduce. Is there more detailed information available? Two specific dates?

**Comment by Mark-Simulacrum** [comment] 2016-09-02 22:54
Okay, from what I can tell this no longer fatal errors but does not show the difference between all crates. This brings up the question: What should be shown when one of the dates did not have that crate built?

**Comment by nrc** [comment] 2016-09-03 01:04
For the compare page in particular, we just need to show an error for the missing build, ideally we would show the results for the build that did work. Even more ideally, we would do this per crate, so we would show either a result if there is one or an error for each crate.

re the earlier comment, I don't have any specific dates to hand, but it was fairly easy to reproduce - just find a date which doesn't exist in the main graph and enter it as one of the compare dates. If that works now, then I'd consider this fixed.

**Comment by Mark-Simulacrum** [comment] 2016-09-03 01:07
This is the current state, I think it's probably good enough to close this. (I think showing an error is good, but we need to fix #68 first.

![image](https://cloud.githubusercontent.com/assets/5047365/18221733/444ead12-7140-11e6-9ca3-5c17cdf6cba9.png)

**Comment by Mark-Simulacrum** [comment] 2016-09-03 01:07
Crates that didn't build either time are just silently ignored at the moment.

**Comment by Mark-Simulacrum** [comment] 2016-09-03 02:53
Okay, this is the new comparison view. Would appreciate feedback.
![image](https://cloud.githubusercontent.com/assets/5047365/18222266/52332b92-714f-11e6-83b2-53ce865ccfa0.png)

**Comment by nrc** [comment] 2016-09-05 00:47
new comparison looks great. Should the 0MB usages be `-` also?

**Comment by Mark-Simulacrum** [comment] 2016-09-05 01:04
Fixed in #84 (squashed it with the comparison-affecting commit).

**Closed** 2016-09-06 06:02 UTC
